PROMPT_MAPPING = {
    "📅 Summarize the Schedule of Activities (SOA)": "Provide a detailed summary of the Schedule of Activities (SOA) in the clinical trial protocol, including study length overview, required activities and assessments, and their timepoints. Include information on screening, enrollment, and maintenance phases.",
    "📝 Key ICF considerations": "List and explain all key Informed Consent Form (ICF) considerations for this clinical trial, including optional ICFs, optional collections, and investigator signature requirements.",
    "🎲 Randomization process and requirements": "Describe the randomization process in detail, including the use of IRT/IWRS systems and the sequence of events that must occur prior to randomization. Include any stratification factors.",
    "🔄 Assessment frequency during maintenance": "Detail the frequency of visits, labs, ECGs, TPV procedures, and IP dispensation during the maintenance/on-study phase. Include information on physical exam types, vital sign specifics, and whether visits are onsite or remote.",
    "🧪 Lab requirements (safety labs, PK sampling)": "Provide a comprehensive overview of all laboratory requirements, including safety labs (CMP, CBC, Coag, Urinalysis), eligibility labs, and PK sampling. Include details on central vs. local testing, and turnaround times.",
    "🧬 Specimen collection details": "Describe the collection details for all specimen types (blood, urine, stool, tissue, nasopharyngeal), including equipment used, collection techniques, and any specific handling instructions.",
    "🧊 Sample processing, storage, and shipping": "Explain the protocols for processing, storing, and shipping all biological samples collected during the trial. Include details on centrifugation, aliquoting, storage conditions, shipping methods, and any special requirements.",
    "🏥 TPV procedures": "List all Third Party Vendor (TPV) procedures involved in the trial (e.g., endoscopy, MRI, CT, ultrasound, liver biopsy, DEXA), including procedure details, result turnaround times, and site-level considerations.",
    "🎓 Required trainings (site and study level)": "Enumerate all required trainings for both site-level and study-level personnel. Include general trainings (e.g., GCP, IATA, HIPAA) as well as study-specific trainings (e.g., protocol, laboratory manual, EDC, IRT).",
    "💊 IP requirements (storage, preparation, accountability)": "Provide a thorough explanation of all Investigational Product (IP) requirements, including storage conditions, preparation and administration procedures, route of administration, and accountability procedures.",
    "⏱️ Study windows and duration": "Describe the study windows in detail, including their length and whether extensions are permitted. Provide information on the overall duration of the study and any extension policies.",
    "🔍 Screening and eligibility assessments": "Detail all assessments and procedures required during the screening phase of the trial. Include information on eligibility labs and how screening timelines align with lab result turnaround times.",
    "🏷️ Local lab requirements and setup": "Specify requirements for local labs, including what tests are to be performed locally, vendor establishment process, CLIA certification, reference ranges, and Lab Manager CV requirements.",
    "🖥️ System access requirements": "List all systems that site staff will need to access during the trial, including EDC, IRT, lab portals, eDiary portals, imaging portals, and any study/CRO specific systems.",
    "⏳ Results turnaround times and implications": "Provide information on turnaround times for various results (e.g., safety labs, eligibility labs, TPV procedure results) and how these timelines impact study windows and patient flow."
}
